"""empty message

Revision ID: 29ee064f0dd9
Revises: c8f31c4cec9f
Create Date: 2022-09-10 14:33:41.770410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29ee064f0dd9'
down_revision = 'c8f31c4cec9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favourites', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favourites', 'characters_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favourites', 'planets_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favourites', 'planets_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favourites', 'characters_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favourites', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
